// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707164232_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.DomainObjects.OneTimePassword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("TargetRole")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("OneTimePasswords");
                });

            modelBuilder.Entity("Domain.DomainObjects.Progresses.ExerciseProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CompletedExercises")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ExerciseProgresses", (string)null);
                });

            modelBuilder.Entity("Domain.DomainObjects.Progresses.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ToolImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Levels", (string)null);
                });

            modelBuilder.Entity("Domain.DomainObjects.Progresses.RoomProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CompletedRooms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RoomProgresses", (string)null);
                });

            modelBuilder.Entity("Domain.DomainObjects.Progresses.UserProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProgresses", (string)null);
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.BaseExercise.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Exercises", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.ExerciseHelper.ClickableArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("ClickableAreas", (string)null);
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.ExerciseHelper.DragAndDropMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DropZoneId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("DragAndDropMappings", (string)null);
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.ExerciseHelper.DraggableItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("DraggableItems", (string)null);
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.ExerciseHelper.DropZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("DropZones", (string)null);
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.ExerciseHelper.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LeftItem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LinkingExerciseIdCorrect")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LinkingExerciseIdLeft")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LinkingExerciseIdRight")
                        .HasColumnType("uuid");

                    b.Property<string>("RightItem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LinkingExerciseIdCorrect");

                    b.HasIndex("LinkingExerciseIdLeft");

                    b.HasIndex("LinkingExerciseIdRight");

                    b.ToTable("Links", (string)null);
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.ExerciseHelper.MCOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MultipleChoiceMultiAnswerExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("MultipleChoiceMultiAnswerExerciseId");

                    b.ToTable("MCOptions", (string)null);
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompletionExperiencePoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<int>("UnlockLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("Domain.DomainObjects.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Persistence.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.ClickableImageExercise", b =>
                {
                    b.HasBaseType("Domain.DomainObjects.Topics.Exercises.BaseExercise.Exercise");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("ClickableImageExercises", (string)null);
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.DragAndDropExercise", b =>
                {
                    b.HasBaseType("Domain.DomainObjects.Topics.Exercises.BaseExercise.Exercise");

                    b.ToTable("DragAndDropExercises", (string)null);
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.LinkingExercise", b =>
                {
                    b.HasBaseType("Domain.DomainObjects.Topics.Exercises.BaseExercise.Exercise");

                    b.ToTable("LinkingExercises", (string)null);
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.MultipleChoiceMultiAnswerExercise", b =>
                {
                    b.HasBaseType("Domain.DomainObjects.Topics.Exercises.BaseExercise.Exercise");

                    b.ToTable("MultipleChoiceExercises", (string)null);
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.BaseExercise.Exercise", b =>
                {
                    b.HasOne("Domain.DomainObjects.Topics.Room", null)
                        .WithMany("Exercises")
                        .HasForeignKey("RoomId");
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.ExerciseHelper.ClickableArea", b =>
                {
                    b.HasOne("Domain.DomainObjects.Topics.Exercises.ClickableImageExercise", null)
                        .WithMany("ClickableAreas")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.ExerciseHelper.DragAndDropMapping", b =>
                {
                    b.HasOne("Domain.DomainObjects.Topics.Exercises.DragAndDropExercise", null)
                        .WithMany("CorrectMappings")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.ExerciseHelper.DraggableItem", b =>
                {
                    b.HasOne("Domain.DomainObjects.Topics.Exercises.DragAndDropExercise", null)
                        .WithMany("Items")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.ExerciseHelper.DropZone", b =>
                {
                    b.HasOne("Domain.DomainObjects.Topics.Exercises.DragAndDropExercise", null)
                        .WithMany("Zones")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.ExerciseHelper.Link", b =>
                {
                    b.HasOne("Domain.DomainObjects.Topics.Exercises.LinkingExercise", null)
                        .WithMany("CorrectLinks")
                        .HasForeignKey("LinkingExerciseIdCorrect")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.DomainObjects.Topics.Exercises.LinkingExercise", null)
                        .WithMany("LeftItems")
                        .HasForeignKey("LinkingExerciseIdLeft")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.DomainObjects.Topics.Exercises.LinkingExercise", null)
                        .WithMany("RightItems")
                        .HasForeignKey("LinkingExerciseIdRight")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.ExerciseHelper.MCOption", b =>
                {
                    b.HasOne("Domain.DomainObjects.Topics.Exercises.MultipleChoiceMultiAnswerExercise", null)
                        .WithMany("CorrectOptionIds")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.DomainObjects.Topics.Exercises.MultipleChoiceMultiAnswerExercise", null)
                        .WithMany("Options")
                        .HasForeignKey("MultipleChoiceMultiAnswerExerciseId");
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Room", b =>
                {
                    b.HasOne("Domain.DomainObjects.Topics.Topic", null)
                        .WithMany("Rooms")
                        .HasForeignKey("TopicId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Persistence.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Persistence.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Persistence.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.ClickableImageExercise", b =>
                {
                    b.HasOne("Domain.DomainObjects.Topics.Exercises.BaseExercise.Exercise", null)
                        .WithOne()
                        .HasForeignKey("Domain.DomainObjects.Topics.Exercises.ClickableImageExercise", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.DragAndDropExercise", b =>
                {
                    b.HasOne("Domain.DomainObjects.Topics.Exercises.BaseExercise.Exercise", null)
                        .WithOne()
                        .HasForeignKey("Domain.DomainObjects.Topics.Exercises.DragAndDropExercise", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.LinkingExercise", b =>
                {
                    b.HasOne("Domain.DomainObjects.Topics.Exercises.BaseExercise.Exercise", null)
                        .WithOne()
                        .HasForeignKey("Domain.DomainObjects.Topics.Exercises.LinkingExercise", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.MultipleChoiceMultiAnswerExercise", b =>
                {
                    b.HasOne("Domain.DomainObjects.Topics.Exercises.BaseExercise.Exercise", null)
                        .WithOne()
                        .HasForeignKey("Domain.DomainObjects.Topics.Exercises.MultipleChoiceMultiAnswerExercise", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Room", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Topic", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.ClickableImageExercise", b =>
                {
                    b.Navigation("ClickableAreas");
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.DragAndDropExercise", b =>
                {
                    b.Navigation("CorrectMappings");

                    b.Navigation("Items");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.LinkingExercise", b =>
                {
                    b.Navigation("CorrectLinks");

                    b.Navigation("LeftItems");

                    b.Navigation("RightItems");
                });

            modelBuilder.Entity("Domain.DomainObjects.Topics.Exercises.MultipleChoiceMultiAnswerExercise", b =>
                {
                    b.Navigation("CorrectOptionIds");

                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
